spring:
  freemarker:
    exposeSessionAttributes: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotr?createDatabaseIfNotExist=true
    username: root
    password: root
    maxActive: 150
    maxIdle: 10
    minIdle: 5
    initialSize: 5
    minEvictableIdleTimeMillis: 1800000
    timeBetweenEvictionRunsMillis: 1800000
    maxWait: 10000
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
  jpa:
    generateDdl: true
  social:
    facebook:
      appId: 384608611709172
      appSecret: b3e8e95bd887a5fdb841d91367696baf

server:
  port: 8080
  address: 0.0.0.0

security:
  user:
    role: ADMIN
    name: admin
    password: admin
  enableCsrf: true


