spring:
  freemarker:
    exposeSessionAttributes: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotr?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generateDdl: true

server:
  port: 8080
  address: 0.0.0.0

security:
  user:
    role: ADMIN
    name: admin
    password: admin
  enableCsrf: true
  
endpoints:
  shutdown:
    enabled: true

http:
  mappers:
    jsonPrettyPrint: true

mail:
  host: smtp.mandrillapp.com
  port: 587
  user: scottiecagno@gmail.com
  pass: AyRsB5cI5H4bcrbheDKfzQ