<script type='text/javascript' src='/static/asher/js/jquery.js'></script>
<script type='text/javascript' src='/static/asher/js/bootstrap.js'></script>
<script type='text/javascript' src='/static/asher/js/jquery.fitvids.js'></script>
<script type='text/javascript' src='/static/asher/js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='/static/asher/js/common.js'></script>
<script type='text/javascript' src='/static/asher/js/flexslider.js'></script>
<script type='text/javascript' src='/static/asher/js/flexsliderhome.js'></script>
<script type='text/javascript' src='/static/asher/js/prettyPhoto.js'></script>
<script type='text/javascript' src='/static/asher/js/flexslidertestimonials.js'></script>
<script type='text/javascript' src='/static/asher/js/testimonial.js'></script>